server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://methionine.org:3306/memorandum?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: me
    password: 658571
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
